Name: Emily Savoie

Labpartner(s): Maya Maes-Johnson

In [68]:
# import statements go here
import numpy as np
import pandas as pd

# Class 4.2

## Today you all are going to do the lecture! It's Present Your Plots Day.

# Warmups 4.2

### Warmup is short today so we have time to focus on your plots.

**W.1** Do Exercise 3 in practice python https://www.practicepython.org

In [9]:
a = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]

for num in a:
    if num < 5:
        print(num)

1
1
2
3

In [17]:
a2 = []

for num in a:
    if num < 5:
        a2.append(num)

print(a2)

[1, 1, 2, 3]

In [19]:
a3 = []

num = int(input('Enter a number: '))
for n in a:
    if n < num:
        a3.append(n)
print(a3)

Enter a number:  55

[1, 1, 2, 3, 5, 8, 13, 21, 34]

## Agenda:

- Questions about class or coding
- Show us your plots! Explain your data set, what you did with it, and what your learned, including any difficulties you had and how you solved them.

# Lab 4.2

**E.1** Complete intermediate python chapter 4: Loops

Note that loops often are very confusing for new programmers, but they are very powerful and super-useful. You will be seing them again.

Note that the tutorials here have similar material for your needs:
https://github.com/chsharrison/Sci_comp_F26/blob/main/Course_materials/resources.md

**E.2** Make notes for yourself on all of the progamming tecniques and commands you learned in the datacamp chapter above, including examples, comments and explainitory text. You might use the resources linked above for supplementary examples. You can do this here or in a separate notebook that you link to here. Basically, you are making a cheat sheet for yourself.

while loops are similar to if statements except it will continue to execute the command for as long as the conidition is true. The syntax for while loops is as follows:  
while condition:  
    &emsp;expression

You are able to run conditional statements inside loops.

In [56]:
offset = 8

while offset != 0:
    print('adjusting')
    offset = offset - 1
    print(offset)

adjusting
7
adjusting
6
adjusting
5
adjusting
4
adjusting
3
adjusting
2
adjusting
1
adjusting
0

In [57]:
offset = -8

while offset !=0:
    print('adjusting')
    if offset > 0:
        offset = offset - 1
    else:
        offset = offset + 1
    print(offset)

adjusting
-7
adjusting
-6
adjusting
-5
adjusting
-4
adjusting
-3
adjusting
-2
adjusting
-1
adjusting
0

for loops allow for iterative calls over a sequence. You specify the variable to use in the for loop syntax.

for var in seq:  
    &emsp;expression

When using for loops on lists, the var name is arbitrary. When a list of lists is used, the arbitrary names are assigned in the order they are listed.

In [58]:
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

for a in areas:
    print(a)

11.25
18.0
20.0
10.75
9.5

In [60]:
# Use enumerate() to add the index to the output and a print statement to format it
# Adjust so index starts at 1 not 0
for index, a in enumerate(areas):
    print('room ' + str(index + 1) + ': ' + str(a))

room 1: 11.25
room 2: 18.0
room 3: 20.0
room 4: 10.75
room 5: 9.5

In [61]:
# Example with a list of lists
house = [["hallway", 11.25], 
         ["kitchen", 18.0], 
         ["living room", 20.0], 
         ["bedroom", 10.75], 
         ["bathroom", 9.50]]

for room, area in house:
    print('the ' + room + ' is ' + str(area) + ' sqm')

the hallway is 11.25 sqm
the kitchen is 18.0 sqm
the living room is 20.0 sqm
the bedroom is 10.75 sqm
the bathroom is 9.5 sqm

You can use for loops over other data structures like NumPy arrays and dictionaries. To do this, you have to adjust the sequence call. 

For disctionaries to go through each key and value, you use the items() method. The variable names are still arbitrary for dictionaries and are used in the order they are listed in the call.

In [62]:
europe = {'spain':'madrid', 'france':'paris', 'germany':'berlin',
          'norway':'oslo', 'italy':'rome', 'poland':'warsaw', 'austria':'vienna' }

for key, val in europe.items():
    print('the capital of ' + key + ' is ' + val)

the capital of spain is madrid
the capital of france is paris
the capital of germany is berlin
the capital of norway is oslo
the capital of italy is rome
the capital of poland is warsaw
the capital of austria is vienna

1D NumPy arrays generally follow the same syntax as lists. 

2D NumPy arrays you use np.nditer(array).

In [65]:
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
bmi = np_weight/np_height ** 2

for val in bmi:
    print(val)

21.85171572722109
20.97505668934241
21.750282138093777
24.74734749867025
21.44127836209856

In [66]:
meas = np.array([np_height, np_weight])

for val in np.nditer(meas):
    print(val)

1.73
1.68
1.71
1.89
1.79
65.4
59.2
63.6
88.4
68.7

When using loops on Pandas DataFrame, you have to specify if you want to iterate over the rows using the iterrows() method on the dataframe you want to look at. This will generate the label and data for the specified row as a Panda Series. You can use column names to specify what exactly you want from each row. Things you can do to Panda DataFrames using loops:  
* Add a column
* Data clean up such as identifying outlier values and such
* Removing rows
* Replacing wrong values/typos

If making a new column based on element wise function done to another column, you can use apply() following this syntax:  
df['new_col'] = df['col'].apply(function)

In [85]:
pop = pd.read_csv('populations.txt', sep = '\t', index_col = 0)
pop

           hare     lynx  carrot
# year
1900    30000.0   4000.0   48300
1901    47200.0   6100.0   48200
1902    70200.0   9800.0   41500
1903    77400.0  35200.0   38200
1904    36300.0  59400.0   40600
1905    20600.0  41700.0   39800
1906    18100.0  19000.0   38600
1907    21400.0  13000.0   42300
1908    22000.0   8300.0   44500
1909    25400.0   9100.0   42100
1910    27100.0   7400.0   46000
1911    40300.0   8000.0   46800
1912    57000.0  12300.0   43800
1913    76600.0  19500.0   40900
1914    52300.0  45700.0   39400
1915    19500.0  51100.0   39000
1916    11200.0  29700.0   36700
1917     7600.0  15800.0   41800
1918    14600.0   9700.0   43300
1919    16200.0  10100.0   41300
1920    24700.0   8600.0   47300

In [74]:
for lab, row in pop.iterrows():
    print(lab, row)

1900 hare      30000.0
lynx       4000.0
carrot    48300.0
Name: 1900, dtype: float64
1901 hare      47200.0
lynx       6100.0
carrot    48200.0
Name: 1901, dtype: float64
1902 hare      70200.0
lynx       9800.0
carrot    41500.0
Name: 1902, dtype: float64
1903 hare      77400.0
lynx      35200.0
carrot    38200.0
Name: 1903, dtype: float64
1904 hare      36300.0
lynx      59400.0
carrot    40600.0
Name: 1904, dtype: float64
1905 hare      20600.0
lynx      41700.0
carrot    39800.0
Name: 1905, dtype: float64
1906 hare      18100.0
lynx      19000.0
carrot    38600.0
Name: 1906, dtype: float64
1907 hare      21400.0
lynx      13000.0
carrot    42300.0
Name: 1907, dtype: float64
1908 hare      22000.0
lynx       8300.0
carrot    44500.0
Name: 1908, dtype: float64
1909 hare      25400.0
lynx       9100.0
carrot    42100.0
Name: 1909, dtype: float64
1910 hare      27100.0
lynx       7400.0
carrot    46000.0
Name: 1910, dtype: float64
1911 hare      40300.0
lynx       8000.0
carrot    46800.0
Name: 1911, dtype: float64
1912 hare      57000.0
lynx      12300.0
carrot    43800.0
Name: 1912, dtype: float64
1913 hare      76600.0
lynx      19500.0
carrot    40900.0
Name: 1913, dtype: float64
1914 hare      52300.0
lynx      45700.0
carrot    39400.0
Name: 1914, dtype: float64
1915 hare      19500.0
lynx      51100.0
carrot    39000.0
Name: 1915, dtype: float64
1916 hare      11200.0
lynx      29700.0
carrot    36700.0
Name: 1916, dtype: float64
1917 hare       7600.0
lynx      15800.0
carrot    41800.0
Name: 1917, dtype: float64
1918 hare      14600.0
lynx       9700.0
carrot    43300.0
Name: 1918, dtype: float64
1919 hare      16200.0
lynx      10100.0
carrot    41300.0
Name: 1919, dtype: float64
1920 hare      24700.0
lynx       8600.0
carrot    47300.0
Name: 1920, dtype: float64

In [77]:
# ID the max value for each year
for lab, row in pop.iterrows():
    print(str(lab) + ': ' + str(row.max()))

1900: 48300.0
1901: 48200.0
1902: 70200.0
1903: 77400.0
1904: 59400.0
1905: 41700.0
1906: 38600.0
1907: 42300.0
1908: 44500.0
1909: 42100.0
1910: 46000.0
1911: 46800.0
1912: 57000.0
1913: 76600.0
1914: 52300.0
1915: 51100.0
1916: 36700.0
1917: 41800.0
1918: 43300.0
1919: 41300.0
1920: 47300.0

In [86]:
# Add a new column with the max population for each year and have the first letter capitalized
pop['Max population'] = pop.idxmax(axis = 1).apply(str.capitalize)
pop

           hare     lynx  carrot Max population
# year
1900    30000.0   4000.0   48300         Carrot
1901    47200.0   6100.0   48200         Carrot
1902    70200.0   9800.0   41500           Hare
1903    77400.0  35200.0   38200           Hare
1904    36300.0  59400.0   40600           Lynx
1905    20600.0  41700.0   39800           Lynx
1906    18100.0  19000.0   38600         Carrot
1907    21400.0  13000.0   42300         Carrot
1908    22000.0   8300.0   44500         Carrot
1909    25400.0   9100.0   42100         Carrot
1910    27100.0   7400.0   46000         Carrot
1911    40300.0   8000.0   46800         Carrot
1912    57000.0  12300.0   43800           Hare
1913    76600.0  19500.0   40900           Hare
1914    52300.0  45700.0   39400           Hare
1915    19500.0  51100.0   39000           Lynx
1916    11200.0  29700.0   36700         Carrot
1917     7600.0  15800.0   41800         Carrot
1918    14600.0   9700.0   43300         Carrot
1919    16200.0  10100.0   41300         Carrot
1920    24700.0   8600.0   47300         Carrot

**E.3-6** Exercises 4-7 in practice python (see link above)

**E.3**

In [27]:
num = int(input())
i = 1
div = []

for i in range(1, num+1):
    if num % i == 0:
        div.append(i)

print(div)

 56

[1, 2, 4, 7, 8, 14, 28, 56]

**E.4**

In [33]:
n = 12
a = np.random.randint(1, 21, size = n).tolist()
a

[4, 7, 16, 19, 7, 2, 20, 4, 19, 1, 19, 7]

In [34]:
n2 = 15
b = np.random.randint(1, 21, size = n).tolist()
b

[19, 19, 19, 15, 5, 6, 4, 20, 13, 13, 9, 5]

In [39]:
c = []

for x in a:
    if x in b and x not in c:
        c.append(x)

print(c)

[4, 19, 20]

**E.5**

In [51]:
word = input('Write a word: ')
word = str(word)
# [::-1] tells python to go backwards through a string, one element at a time.
rev = word[::-1]

if word == rev:
    print(word + ' is a palindrome!')
else:
    print(word + ' is not a palindrome.')

Write a word:  wow

wow is a palindrome!

In [52]:
word = input('Write a word: ')
word = str(word)
# [::-1] tells python to go backwards through a string, one element at a time.
rev = word[::-1]

if word == rev:
    print(word + ' is a palindrome!')
else:
    print(word + ' is not a palindrome.')

Write a word:  dog

dog is not a palindrome.

**E.6**

In [55]:
a = [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

evens = [num for num in a if num % 2 == 0]
evens

[4, 16, 36, 64, 100]