Name: Emily Savoie

Labpartner(s): Maru Shapiro

In [ ]:
#import statements go here
import numpy as np
import pandas as pd

# Class 9.1

I'm out sick today, but you all are advanced so I know you will be productive without me.

# Warmup 9.1

**W.1** Create the following numpy array. Print out the values to check!

[[0. 0. 0. 0. 0. 0. 0.]

[0. 1. 1. 1. 1. 1. 0.]

[0. 1. 1. 1. 1. 1. 0.]

[0. 1. 1. 5. 1. 1. 0.]

[0. 1. 1. 1. 1. 1. 0.]

[0. 1. 1. 1. 1. 1. 0.]

[0. 0. 0. 0. 0. 0. 0.]]

In [2]:
array = np.zeros((7,7))
array

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [3]:
array[1:6] = array[1:6] + 1
array

array([[0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [4]:
array[3,3] = array [3,3] + 4
array

array([[0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 5., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0.]])

**W.2** Pandas filtering and sorting practice with Chipotle data

Import the dataset from this address https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv
Assign it to a variable called chipo.
1. How many products cost more than $10.00?
2. What is the price of each item?
    1. Print a data frame with only two columns item_name and item_price
    2. Sort by the name of the item
1. What was the quantity of the most expensive item ordered?
1. How many times did someone order more than one Canned Soda?

In [35]:
data = pd.read_table('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv')
data

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [40]:
# How many products cost more than $10?

data2 = data.drop_duplicates(subset = ['item_name', 'item_price'])
data2['item_price']= data2['item_price'].replace('[\$,]','', regex=True).astype(float)
data2.value_counts(data2['item_price']>10)

item_price
False    112
True      97
Name: count, dtype: int64

With item name and price combo duplicates removed, 97 items ordered were greater than $10.

In [56]:
# What is the price of each item? Print a data frame with only two columns item_name and item_price. Sort by the name of the item.
# Unique combos of name and price
data3 = data2[['item_name','item_price']]
data3 = data3.sort_values(by = 'item_name')
print(data3)

              item_name  item_price
298   6 Pack Soft Drink        6.49
3389  6 Pack Soft Drink       12.98
39        Barbacoa Bowl       11.75
95        Barbacoa Bowl        9.25
115       Barbacoa Bowl        8.99
...                 ...         ...
960   Veggie Salad Bowl        8.75
738   Veggie Soft Tacos       11.25
781   Veggie Soft Tacos        8.75
1395  Veggie Soft Tacos        8.49
3889  Veggie Soft Tacos       16.98

[209 rows x 2 columns]

In [49]:
# Unique combos of name and price above $10
data4 = data2[['item_name','item_price']]
data4 = data4[data4['item_price']>10]
data4 = data4.sort_values(by = 'item_name')
print(data4)

              item_name  item_price
3389  6 Pack Soft Drink       12.98
39        Barbacoa Bowl       11.75
471       Barbacoa Bowl       11.48
4510      Barbacoa Bowl       11.49
130    Barbacoa Burrito       11.75
...                 ...         ...
435      Veggie Burrito       10.98
3601     Veggie Burrito       33.75
186   Veggie Salad Bowl       11.25
738   Veggie Soft Tacos       11.25
3889  Veggie Soft Tacos       16.98

[97 rows x 2 columns]

In [52]:
# What was the quantity of the most expensive item ordered?
data5 = data2[data2['item_price'] == data2['item_price'].max()]
data5

,order_id,quantity,item_name,choice_description,item_price
3598,1443,15,Chips and Fresh Tomato Salsa,NaN,44.25

The quantity ordered for the most expensive item was 15.

In [55]:
# How many times did someone order more than one Canned Soda?
data6 = data[data['item_name']=='Canned Soda']
print(data6.value_counts(data6['quantity']>1))

quantity
False    84
True     20
Name: count, dtype: int64

More than one canned soda was ordered 20 times.

# Lecture 9.1

### Agenda:

- Questions
- Exchange proposal outlines with your labmate.
- LaTeX tutorial

### Questions

If you have questions, please pose them to the class. You can also send me a slack message.

# Lab 9.1

**E.0** Complete the previous labs if you are behind.

**E.1** Share your proposal outline with your lab partner. Give each other fedback. Consult the rubric and checklist. Do you have all the graded components? What needs work?

**E.2** Complete the tutorial "Learn LaTeX in 30 min" here: https://www.overleaf.com/learn/latex/Learn_LaTeX_in_30_minutes

Make a sample document in LaTeX showing what you learned and submit the PDF along with your lab in Moodle.

**E.3** Using a CV template in Overleaf, make an academic CV for yourself. Put the PDF of your CV on github and link in Moodle

**E.4** Ask your supervisor for a proposal sample. This could be a proposal another student in your lab has written, or a proposal your PI has written. Use this to inform your proposal writing style. If it's okay with your PI to share, upload it onto github to share with others in the class and submit a link. If it's not for sharing, upload a copy to Moodle. You can consult previous class' github for more samples.

**Notes** Make notes for yourself on progamming tecniques and commands you learned in the this week, including examples, comments and explainitory text. You can do this here or in a separate notebook that you link to here. Basically, you are making a cheat sheet for yourself.

[Reference Notebook]('Reference_notebook.ipynb')