Name

Labpartner(s)

In [19]:
#import statements go here

# Class 9.1

I'm out sick today, but you all are advanced so I know you will be productive without me.

# Warmup 9.1

**W.1** Create the following numpy array. Print out the values to check!

[[0. 0. 0. 0. 0. 0. 0.]

[0. 1. 1. 1. 1. 1. 0.]

[0. 1. 1. 1. 1. 1. 0.]

[0. 1. 1. 5. 1. 1. 0.]

[0. 1. 1. 1. 1. 1. 0.]

[0. 1. 1. 1. 1. 1. 0.]

[0. 0. 0. 0. 0. 0. 0.]]

In [14]:
import numpy as np
zero = np.zeros((7,7))
zero

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [15]:
zero[1:6, 1:6] = zero[1:6, 1:6] + 1
zero

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [16]:
zero[3:4, 3:4] = zero[3:4, 3:4] *5
# or: zero [3,3] = zero[3,3] +4
zero

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 5., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

**W.2** Pandas filtering and sorting practice with Chipotle data

Import the dataset from this address https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv
Assign it to a variable called chipo.
1. How many products cost more than $10.00?
2. What is the price of each item?
    1. Print a data frame with only two columns item_name and item_price
    2. Sort by the name of the item
1. What was the quantity of the most expensive item ordered?
1. How many times did someone order more than one Canned Soda?

In [86]:
import pandas as pd
chipo = pd.read_table("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv")
chipo.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [75]:
#remove $ from the item price
chipo['item_price'] = chipo['item_price'].map(lambda x: x.lstrip('$').rstrip('aAbBcC'))
chipo.head()
#turn item price into float values 
chipo['item_price'] = (chipo['item_price']).astype(float)

In [34]:
# collect item price values larger than 10
more_than_ten = chipo[chipo['item_price'] >10]
#Assuming that item price is the cost of one of item name and then quanity is how many were ordered total per order?

In [35]:
items = more_than_ten['item_name'].unique()
print(items)
#31 items that cost more than 10 dollars

<ArrowStringArray>
[                'Chicken Bowl',                'Steak Burrito',
              'Chicken Burrito',                'Barbacoa Bowl',
               'Veggie Burrito',                  'Veggie Bowl',
           'Chicken Soft Tacos',                   'Steak Bowl',
             'Carnitas Burrito',                'Carnitas Bowl',
             'Barbacoa Burrito',           'Chicken Salad Bowl',
        'Barbacoa Crispy Tacos',            'Veggie Salad Bowl',
         'Chicken Crispy Tacos',                'Chicken Salad',
             'Steak Salad Bowl',                         'Bowl',
            'Veggie Soft Tacos',          'Barbacoa Soft Tacos',
        'Carnitas Crispy Tacos',          'Carnitas Salad Bowl',
          'Barbacoa Salad Bowl', 'Chips and Fresh Tomato Salsa',
             'Steak Soft Tacos',          'Carnitas Soft Tacos',
           'Steak Crispy Tacos',          'Chips and Guacamole',
            '6 Pack Soft Drink',                'Bottled Water',
                'Side of Chips']
Length: 31, dtype: str

In [65]:
parced = chipo[['item_name', 'item_price']].copy()
#parced = parced.set_index('item_name')
parced_sort = parced.sort_values('item_name')
parced_sort.head()
parced_sort.drop_duplicates(subset = ['item_name', 'item_price'])

              item_name item_price
298   6 Pack Soft Drink     $6.49
3389  6 Pack Soft Drink    $12.98
39        Barbacoa Bowl    $11.75
95        Barbacoa Bowl     $9.25
115       Barbacoa Bowl     $8.99
...                 ...        ...
960   Veggie Salad Bowl     $8.75
738   Veggie Soft Tacos    $11.25
781   Veggie Soft Tacos     $8.75
1395  Veggie Soft Tacos     $8.49
3889  Veggie Soft Tacos    $16.98

[209 rows x 2 columns]

In [76]:
chipo.head()
chipo_ordered_price = chipo.sort_values('item_price', ascending = False)
chipo_ordered_price.head()
#15 orders of chips and fresh tomato salsa for 44 dollars!!

,order_id,quantity,item_name,choice_description,item_price
3598,1443,15,Chips and Fresh Tomato Salsa,NaN,44.25
3480,1398,3,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",35.25
3602,1443,4,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",35.00
1254,511,4,Chicken Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",35.00
3601,1443,3,Veggie Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",33.75

In [89]:
chipo.head()
canned_soda = chipo[chipo['item_name'] == 'Canned Soda']
canned_soda.head()
canned_soda.value_counts(canned_soda['quantity']>1)
#someone ordered more than 1 canned soda 20 times

quantity
False    84
True     20
Name: count, dtype: int64

# Lecture 9.1

### Agenda:

- Questions
- Exchange proposal outlines with your labmate.
- LaTeX tutorial

### Questions

If you have questions, please pose them to the class. You can also send me a slack message.

# Lab 9.1

**E.0** Complete the previous labs if you are behind.

**E.1** Share your proposal outline with your lab partner. Give each other fedback. Consult the rubric and checklist. Do you have all the graded components? What needs work?

**E.2** Complete the tutorial "Learn LaTeX in 30 min" here: https://www.overleaf.com/learn/latex/Learn_LaTeX_in_30_minutes

Make a sample document in LaTeX showing what you learned and submit the PDF along with your lab in Moodle.

**E.3** Using a CV template in Overleaf, make an academic CV for yourself. Put the PDF of your CV on github and link in Moodle

**E.4** Ask your supervisor for a proposal sample. This could be a proposal another student in your lab has written, or a proposal your PI has written. Use this to inform your proposal writing style. If it's okay with your PI to share, upload it onto github to share with others in the class and submit a link. If it's not for sharing, upload a copy to Moodle. You can consult previous class' github for more samples.

**Notes** Make notes for yourself on progamming tecniques and commands you learned in the this week, including examples, comments and explainitory text. You can do this here or in a separate notebook that you link to here. Basically, you are making a cheat sheet for yourself.